apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secrets
  namespace: argocd
spec:
  project: tech-challenge
  source:
    repoURL: https://github.com/j-hashed-gomez/devops-challenge.git
    targetRevision: main
    path: k8s/cluster
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
