apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    chart: cluster-autoscaler
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.43.2
    helm:
      releaseName: cluster-autoscaler
      values: |
        autoDiscovery:
          clusterName: devops-challenge-eks

        awsRegion: eu-west-1

        rbac:
          create: true
          serviceAccount:
            create: true
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::054431466060:role/tech-challenge-cluster-autoscaler-sa"

        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi

        extraArgs:
          logtostderr: true
          stderrthreshold: info
          v: 4
          skip-nodes-with-local-storage: false
          expander: least-waste
          balance-similar-node-groups: true
          skip-nodes-with-system-pods: false

        image:
          repository: registry.k8s.io/autoscaling/cluster-autoscaler
          tag: v1.33.0

        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

        podLabels:
          app: cluster-autoscaler

        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          fsGroup: 65534
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
