apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tech-challenge-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: tech-challenge

  source:
    repoURL: https://github.com/j-hashed-gomez/devops-challenge.git
    targetRevision: staging  # Deploy from staging branch
    path: k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: tech-challenge-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas

  revisionHistoryLimit: 10
